### ISSUE TITLE
NSInvalidArgumentException in UIView(Internal) _addSubview:positioned:relativeTo:

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#30]
Crashlytics #119
SafeSlinger 1.7.1
NEW ISSUE FOUND
UIKit
-[UIView(Internal) _addSubview:positioned:relativeTo:]

Fatal Exception: NSInvalidArgumentException
Can't add self as subview

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x00000001816a7100 __exceptionPreprocess + 132
1  libobjc.A.dylib                0x000000018dbb01fc objc_exception_throw + 60
2  CoreFoundation                 0x00000001816a7040 -[NSException initWithCoder:]
3  UIKit                          0x0000000184677ea0 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 128
4  UIKit                          0x0000000184866adc __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke + 1356
5  UIKit                          0x000000018467ede0 +[UIView(Animation) performWithoutAnimation:] + 88
6  UIKit                          0x00000001848662cc -[_UINavigationParallaxTransition animateTransition:] + 828
7  UIKit                          0x000000018481e034 -[UINavigationController _startCustomTransition:] + 2724
8  UIKit                          0x0000000184727f3c -[UINavigationController _startDeferredTransitionIfNeeded:] + 464
9  UIKit                          0x0000000184727d0c -[UINavigationController __viewWillLayoutSubviews] + 56
10 UIKit                          0x0000000184727c8c -[UILayoutContainerView layoutSubviews] + 200
11 UIKit                          0x000000018466afe0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 348
12 QuartzCore                     0x000000018425c258 -[CALayer layoutSublayers] + 184
13 QuartzCore                     0x0000000184256e20 CA::Layer::layout_if_needed(CA::Transaction*) + 300
14 QuartzCore                     0x0000000184256cd8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
15 QuartzCore                     0x0000000184256560 CA::Context::commit_transaction(CA::Transaction*) + 280
16 QuartzCore                     0x0000000184256304 CA::Transaction::commit() + 424
17 UIKit                          0x000000018466f154 _UIApplicationHandleEventQueue + 9800
18 CoreFoundation                 0x00000001816677f4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
19 CoreFoundation                 0x0000000181666b50 __CFRunLoopDoSources0 + 256
20 CoreFoundation                 0x0000000181664de8 __CFRunLoopRun + 632
21 CoreFoundation                 0x00000001815a5dd0 CFRunLoopRunSpecific + 452
22 GraphicsServices               0x000000018728dc0c GSEventRunModal + 168
23 UIKit                          0x00000001846d6fc4 UIApplicationMain + 1156
24 SafeSlinger                    0x00000001000c8b10 main (main.m:33)
25 libdyld.dylib                  0x000000018e1a3aa0 start + 4

**Comment by tenmalin** [comment]
same issue as https://github.com/SafeSlingerProject/SafeSlinger-iOS/issues/88

**Comment by whsheikh101** [comment]
anyone found this issue solution ?
