### ISSUE TITLE
Exc Bad Access, Kern Invalid Address in SSEngine Sign:withPrikey

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#33]
Crashlytics #117
SafeSlinger 1.7.0
edu.cmu.cylab.safeslinger.app
EVP_PKEY_get1_RSA

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x00000000

Thread : Crashed: com.apple.main-thread
0  SafeSlinger                    0x000d367a EVP_PKEY_get1_RSA
1  SafeSlinger                    0x000421f3 +[SSEngine Sign:withPrikey:] (SSEngine.m:477)
2  SafeSlinger                    0x000421f3 +[SSEngine Sign:withPrikey:] (SSEngine.m:477)
3  SafeSlinger                    0x00043341 +[SSEngine PackMessage:PubKey:Prikey:] (SSEngine.m:837)
4  SafeSlinger                    0x0004410f +[SSEngine BuildCipher:Message:Attach:RawFile:MIMETYPE:Cipher:] (SSEngine.m:1079)
5  SafeSlinger                    0x000201bd -[MessageDetailView sendSecureText:] (MessageDetailView.m:155)
6  SafeSlinger                    0x00025cf3 -[MessageDetailView alertView:clickedButtonAtIndex:] (MessageDetailView.m:851)
7  UIKit                          0x33165209 -[_UIModalItemsCoordinator _notifyDelegateModalItem:tappedButtonAtIndex:] + 144
8  UIKit                          0x33164edb -[_UIModalItemAlertContentView tableView:didSelectRowAtIndexPath:] + 378
9  UIKit                          0x3306c7d3 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1078
10 UIKit                          0x3311ec93 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 214
11 UIKit                          0x32fcdde9 _applyBlockToCFArrayCopiedToStack + 316
12 UIKit                          0x32f46b37 _afterCACommitHandler + 430
13 CoreFoundation                 0x306e7ff9 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
14 CoreFoundation                 0x306e5987 __CFRunLoopDoObservers + 286
15 CoreFoundation                 0x306e5cd3 __CFRunLoopRun + 738
16 CoreFoundation                 0x30650729 CFRunLoopRunSpecific + 524
17 CoreFoundation                 0x3065050b CFRunLoopRunInMode + 106
18 GraphicsServices               0x355bf6d3 GSEventRunModal + 138
19 UIKit                          0x32fb1871 UIApplicationMain + 1136
20 SafeSlinger                    0x00051f0f main (main.m:17)

**Comment by tenmalin** [comment]
Similar issue to https://github.com/SafeSlingerProject/SafeSlinger-iOS/issues/89

**Comment by tenmalin** [comment]
Add additional NULL check for RSA private key loading.
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/8da3c6ec6dd870588cf12d2f272649c8903a6545

**Comment by tenmalin** [comment]
Add additional NULL check for RSA private key loading.
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/8da3c6ec6dd870588cf12d2f272649c8903a6545
