### ISSUE TITLE
Librarian -[LBQuery _willChange:inSet:]

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#43]
Issue #125
Librarian
-[LBQuery _willChange:inSet:]
iPhone 5
8.0.2 iOS version

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x34547f46 objc_msgSend + 5
1  Librarian                      0x2e73dd1d -[LBQuery _willChange:inSet:] + 56
2  Librarian                      0x2e73e7cf -[LBQuery _processUpdates] + 566
3  Librarian                      0x2e73ce09 -[LBQuery _sendNote] + 136
4  Librarian                      0x2e73d37f -[LBQuery __updateQueryResultForURL:info:updateType:] + 742
5  Librarian                      0x2e73d495 __52-[LBQuery _updateQueryResultForURL:info:updateType:]_block_invoke + 36
6  CoreFoundation                 0x26e265b5 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
7  CoreFoundation                 0x26e25879 __CFRunLoopDoBlocks + 216
8  CoreFoundation                 0x26e243b3 __CFRunLoopRun + 1714
9  CoreFoundation                 0x26d72621 CFRunLoopRunSpecific + 476
10 CoreFoundation                 0x26d72433 CFRunLoopRunInMode + 106
11 GraphicsServices               0x2e0e10a9 GSEventRunModal + 136
12 UIKit                          0x2a35d359 UIApplicationMain + 1440
13 SafeSlinger                    0x0010e05b main (main.m:33)

**Comment by brnunes** [comment]
Could not reproduce or even find what could have caused the crash. This crash specifically doesn't give any hint on where in our code is the problem.
