### ISSUE TITLE
Crash in MessageDetailView viewWillAppear:

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#51]
Crashlytics Issue #128
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xfffffffc 

SafeSlinger 1.8.0.1
NEW ISSUE FOUND
MessageDetailView.m line 155
-[MessageDetailView viewWillAppear:]
iPhone 5s
8.1 iOS version

Thread : Crashed: com.apple.main-thread
0  UIKit                          0x2d0f28e0 -[UISectionRowData heightForRow:inSection:canGuess:] + 55
1  UIKit                          0x2d0f28a1 -[UITableViewRowData heightForRow:inSection:canGuess:adjustForReorderedRow:] + 260
2  UIKit                          0x2d0f28a1 -[UITableViewRowData heightForRow:inSection:canGuess:adjustForReorderedRow:] + 260
3  UIKit                          0x2d0f2735 -[UITableViewRowData rectForRow:inSection:heightCanBeGuessed:] + 748
4  UIKit                          0x2d289ddd -[UITableView _rectForRowAtIndexPath:canGuess:] + 116
5  UIKit                          0x2d0f5153 -[UITableView rectForRowAtIndexPath:] + 142
6  UIKit                          0x2d1d0581 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:] + 920
7  UIKit                          0x2d1d01c3 -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 38
8  SafeSlinger                    0x00068cb3 -[MessageDetailView viewWillAppear:] (MessageDetailView.m:155)
9  UIKit                          0x2cfde76b -[UIViewController _setViewAppearState:isAnimating:] + 438
10 UIKit                          0x2d1520b5 -[UINavigationController _startCustomTransition:] + 848
11 UIKit                          0x2d071ee7 -[UINavigationController _startDeferredTransitionIfNeeded:] + 422
12 UIKit                          0x2d071ced -[UINavigationController __viewWillLayoutSubviews] + 44
13 UIKit                          0x2d071c81 -[UILayoutContainerView layoutSubviews] + 184
14 UIKit                          0x2cfc64d7 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 514
15 QuartzCore                     0x2c9eea0d -[CALayer layoutSublayers] + 136
16 QuartzCore                     0x2c9ea3e5 CA::Layer::layout_if_needed(CA::Transaction*) + 360
17 QuartzCore                     0x2c9ea26d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 16
18 QuartzCore                     0x2c9e9c51 CA::Context::commit_transaction(CA::Transaction*) + 224
19 QuartzCore                     0x2c9e9a55 CA::Transaction::commit() + 324
20 QuartzCore                     0x2c9e392d CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 56
21 CoreFoundation                 0x29ad03b5 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
22 CoreFoundation                 0x29acda73 __CFRunLoopDoObservers + 278
23 CoreFoundation                 0x29acde7b __CFRunLoopRun + 914
24 CoreFoundation                 0x29a1c211 CFRunLoopRunSpecific + 476
25 CoreFoundation                 0x29a1c023 CFRunLoopRunInMode + 106
26 GraphicsServices               0x30dd50a9 GSEventRunModal + 136
27 UIKit                          0x2d0281d1 UIApplicationMain + 1440
28 SafeSlinger                    0x0009e05b main (main.m:33)

**Comment by brnunes** [comment]
Problem happened when scrolling to the bottom of the UITableView that shows the messages.
Changed method used to a safer one.
