### ISSUE TITLE
Implement push notification service via Google App Engine

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-iOS#55]
Due to policy changes by Urban Airship, they did not offer developer edition anymore. We plan to manage push notification service by our own.

**Comment by mwfarb** [comment]
Related to https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/issues/4

**Comment by tenmalin** [comment]
Successfully remove urban airship library support and push codes to APNS_dev branch. 
https://github.com/SafeSlingerProject/SafeSlinger-iOS/tree/APNS_dev
Now wait to merge until server code is done.

**Comment by tenmalin** [comment]
Close via merge APNS_dev branch, see https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/b19c3cdc36aa3fc39055dbf7549d72874bc735da
