### ISSUE TITLE
remove compose view from tabs

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#56]
See general discussion started on: https://github.com/SafeSlingerProject/SafeSlinger-Android/issues/91

**Comment by brnunes** [comment]
I created some icons to represent the attachments, take a look and see if you have a better idea.
I also created a new string [here](https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/97f8749c89695fbba3ff5613737ea46b35dbec1a#diff-0959061ac7e237bf237d970b6f4e6d91R883) to clear the attachment in the conversation screen

**Comment by mwfarb** [comment]
Thanks @brnunes, the new string has been pushed to transifex as well.

**Comment by mwfarb** [comment]
This is looking good from my testing @brnunes!  

On Android, the compose view included a small thumbnail (if an image), and the name and size of the attachment. To try and keep those features, I have an attachment icon on my action bar, and then when there is an attachment, I added a small area above the edit box and send button to show these details of the attachment. When they touch the thumbnail/name/size line it shows the File Options menu with Change and Remove as options, and when they touch the attachment icon it shows the Camera/Gallery/PhotoLib type options.

I know the iOS screen is tight, but if the Send button has been freed from the top right navigation button, I wonder if the attachment icon could go up there? That might free some space from the edit box at the bottom. Is it possible then to add a line of attachment details above the edit box and send button that could be dynamically loaded if there is an attachment or not?

I'm almost finished testing this feature in Android, so let me know if you want to do any side by side testing.

**Comment by brnunes** [comment]
I've implemented your suggestion, @mwfarb. Let me know if you think something should be different.

**Comment by mwfarb** [comment]
@brnunes I just tried the new behavior and I love the real estate savings and behavior. It looks really nice!
