### ISSUE TITLE
Crashlytics: ContactManageView crash

### ISSUE THREAD

**Issue by tenmalin** [SafeSlingerProject/SafeSlinger-iOS#64]
ContactManageView.m line 127 
-[ContactManageView viewWillAppear:]

Thread : Crashed: com.apple.main-thread
0  CoreFoundation                 0x000000018351086c CFArrayGetCount + 44
1  SafeSlinger                    0x0000000100010da0 -[ContactManageView viewWillAppear:] (ContactManageView.m:127)
2  SafeSlinger                    0x0000000100010da0 -[ContactManageView viewWillAppear:] (ContactManageView.m:127)
3  UIKit                          0x0000000187df4140 -[UIViewController _setViewAppearState:isAnimating:] + 516
4  UIKit                          0x0000000187f7febc -[UINavigationController _startCustomTransition:] + 916
5  UIKit                          0x0000000187e91630 -[UINavigationController _startDeferredTransitionIfNeeded:] + 468
6  UIKit                          0x0000000187e913fc -[UINavigationController __viewWillLayoutSubviews] + 56
7  UIKit                          0x0000000187e9137c -[UILayoutContainerView layoutSubviews] + 200
8  UIKit                          0x0000000187dd9d2c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 572
9  QuartzCore                     0x0000000187731994 -[CALayer layoutSublayers] + 168
10 QuartzCore                     0x000000018772c564 CA::Layer::layout_if_needed(CA::Transaction*) + 320
11 QuartzCore                     0x000000018772c408 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
12 QuartzCore                     0x000000018772bc08 CA::Context::commit_transaction(CA::Transaction*) + 276
13 QuartzCore                     0x000000018772b98c CA::Transaction::commit() + 436
14 UIKit                          0x0000000187ddbc48 _UIApplicationHandleEventQueue + 1700
15 CoreFoundation                 0x00000001835e69ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
16 CoreFoundation                 0x00000001835e5c90 __CFRunLoopDoSources0 + 264
17 CoreFoundation                 0x00000001835e3d40 __CFRunLoopRun + 712
18 CoreFoundation                 0x00000001835110a4 CFRunLoopRunSpecific + 396
19 GraphicsServices               0x000000018c6b35a4 GSEventRunModal + 168
20 UIKit                          0x0000000187e42aa4 UIApplicationMain + 1488
21 SafeSlinger                    0x0000000100050764 main (main.m:33)
22 libdyld.dylib                  0x00000001943a2a08 start + 4

**Comment by brnunes** [comment]
This is the stack of a crash caused by the problem described on issue #67
