### ISSUE TITLE
user unable to import replacement key after sling

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#66]
Scenario in 1.8.1 for iOS 8 test:
- iOS Alice slings key/reg AK1/AR1 with Bob's key/reg BK1/BR1.
- Alice imports Bob successfully: "1 contacts imported"
- Alice can decrypt Bob's messages.
- Bob forgets passphrase, generates new key BK2.
- iOS Alice slings key/reg AK1/AR1 with Bob's key/reg BK2/BR1.
- Alice fails to import Bob: "0 contacts imported"
- Alice cannot decrypt Bob's messages.

**Comment by brnunes** [comment]
I think this is the same as [issue 52](https://github.com/SafeSlingerProject/SafeSlinger-iOS/issues/52).

**Comment by mwfarb** [comment]
I was wondering about that, thanks for linking it.

**Comment by brnunes** [comment]
Updated 'tokenstore' table in database to have as primary keys the 'ptoken'  push token and the 'keyid'  key id of the public key. Now it is possible to exchange keys with a user which has a push token that is already in the database.
Moved the database update methods to SafeSlingerDB.m. Now updating the databases for all accounts in the device.
