### ISSUE TITLE
update input fields to auto-capitalize

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#70]
We should be consistent for all our TextInput UI fields to auto capitalize whenever possible.
- Messages tab, conversation view compose message box = UITextAutocapitalizationTypeSentences.
- Compose tab, compose message box = UITextAutocapitalizationTypeSentences (appears to be done already).
- Settings tab, first name edit box = UITextAutocapitalizationTypeWords.
- Settings tab, last name edit box = UITextAutocapitalizationTypeWords.
 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextInputTraits_Protocol/index.html#//apple_ref/c/tdef/UITextAutocapitalizationType

**Comment by tenmalin** [comment]
Closed via https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/100f73ed24f046ea227f8fb635764aa85fe7e5fa
