### ISSUE TITLE
Load messages asynchronously in conversation screen (MessageDetailView)

### ISSUE THREAD

**Issue by brnunes** [SafeSlingerProject/SafeSlinger-iOS#72]
When the conversation has many messages, and specially when many messages have attachments, the conversation screen (MessageDetailView) takes too long to load.
This happens because every message is loaded into memory from the UI thread, including the ones with attachments (some attachments might be many MB in size).
The messages should be loaded asynchronously, and the attachments don't need to be loaded until the user touches the message to preview it, since they are not shown.

**Comment by mwfarb** [comment]
@brnunes As discussed, for now it should be enough to alter the query to not load the attachment column during the UI display events, and to load that column only when when the user "taps to open". We can change the storage model in a later release.

**Comment by mwfarb** [comment]
@brnunes With issue #4 closed, it would be good to table this issue until 1.8.3 to get 1.8.2 out the door. Unless you are 95% done with this, what do you think?

**Comment by brnunes** [comment]
@mwfarb I agree. This issue should be simple to solve, but I haven't started it. I'll try to work on it before the weekend, but feel free to change the milestone.

**Comment by tenmalin** [comment]
@brnunes, I am trying to measure time for database operations and table reload actions. I think we have to see which part takes longer. Basically database operation did not pull out file content, just file extension types, file name , and other meta data. 

I will think about how to fetch those data entries in a more efficiency way from our database.

**Comment by tenmalin** [comment]
A quickly way to implement efficient message loading is try to load the last 10 messages and then load the remaindering using another thread and load into memory a bit later.

**Comment by tenmalin** [comment]
For iPhone 5 and up, it takes roughly 0.2 second to load more than 50 messages. I will prefer to move it to the next binary release.

**Comment by tenmalin** [comment]
Optimize the database by:
1. Stop loading all messages again after file preview finishes.
2. Use table entry update while adding/updating/removing messages; we do not update the whole table by reloading messages from the database.
3. For marking message as read, the perforce degrades a lot. Therefore, we move marking flag task to background instead of foreground.

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/81605bacf40c8ef77d9e0f7039c4bc34b1440e79.
