### ISSUE TITLE
disappearing recipient and sending to invalid push type

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#75]
[edited for accuracy 4/22/15]

User (A) SafeSlinger/1.8.1.1
User (A) iOS Model: iPhone
User (A) iPhone OS 6.1.3

User (B) "Add Contact Invite"

User (C) SafeSlinger/1.8.1.1 
User (C) iOS 6

1. A slings keys with C.
1. A sends Add Contact Invite from Compose|SelectRecipient|+ to a random phone contact B.
1. B shows up in A’s recipient list with B's name, but the previous sling keys date of another recipient C.
1. A no longer sees C in the recipient list.
1. C sends a message to A.
1. C receives error message from server: "User has no push registration id".

This last message is from C using push notify type 0, however that occurred.

**Comment by mwfarb** [comment]
I've updated the scenario, basically it appears that the Add Contact Invite is causing either UI or DB corruption int he recipients list.

**Comment by tenmalin** [comment]
It only happens for email invitation.

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/eadb24c9de82fc8eb0328814d2292e4d912aa1b2.
