### ISSUE TITLE
unable to download messages

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#76]
When a user reboots the device, has a power loss, or manually kills the app, when push messages arrive and the user launches the app, the app does not contact the server for getNoncesByToken.

This is an important issue we need to close ASAP. We know some users are having this issue, but were having trouble reproducing it. Now, we have a reproducible case related to cold start.

1. Completely kill the app from running in the background.
1. Push message arrives and shows a notification.
1. Application icon badge number is positive. 
1. Tap the notification or application icon to launch the app.
1. Messages tab shows 0 new messages, and no conversations list the new message.

**Comment by mwfarb** [comment]
I know we're hoping to avoid calling getNoncesByToken very frequently, and I think we can still do that, but we just need to make sure we cover the following cases.

When to call getNoncesByToken, and it doesn’t matter if the user is logged in or not since we’re only downloading ciphertext in both cases:
- On app launch, when badge number is > 0.
- On resume coming from background to foreground, when badge number is > 0.
- On push arrives when app is in the foreground.
- On user manually requests a refresh, by pulling the conversation list all the way to the bottom.
- On user manually requests a refresh, by pulling the threads list all the way to the top.

**Comment by mwfarb** [comment]
This is another effect of the same root cause, but the effect makes it seems that the decrypt process did not work:
- Kill SafeSlinger.
- Receive 2 push messages.
- Badge number is 2.
- Tap application icon.
- Open conversation list on Messages tab.
- No new messages listed.
- Receive 1 more push message.
- Conversation shows 2 new messages with "tap to decrypt", and a Toast error message: "Message expired"
- Tap any one of the "tap to decrypt" messages.
- Conversation still shows 2 new messages with "tap to decrypt", however the message we tapped in the previous steps is now decrypted.

This case will probably be gone once auto-decrypt is implemented.

**Comment by tenmalin** [comment]
Implement a new functionality enabled by manual gesture in thread view, e.g., scroll down the view to fetch possible new messages from the server.

**Comment by mwfarb** [comment]
We are now receiving messages in these cases from @brnunes's fix so I'm closing this. I'll add a new issue for updating the message checking model later in another release to make sure we catch some more rare edge cases when we set the badge number to 0 too early.
