### ISSUE TITLE
remove submission token from postRegistration

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#78]
The server has been upgraded now so that it will accept a 0 length submission token aslong as the new signed public key format is used.

**Comment by tenmalin** [comment]
To @mwfarb, is submission token mandatory for registration? The current registration attaches submission token. If the token data is necessary, I will close this issue.

**Comment by mwfarb** [comment]
@tenmalin The original submission token can be removed now, but the length field is still required and should be set to 0. The order of fields in the new scheme can be:

        lenkeyid = same
        keyId = same
        lensubtok = same (but now always 0)
        lenregid = same
        registrationId = same
        devtype = same
        lennonce = new
        nonce = new
        lenpubkey = new
        pubkey = new   
        sig_len = new
        sig =  new

**Comment by mwfarb** [comment]
From: https://github.com/SafeSlingerProject/SafeSlinger-AppEngine/blob/master/safeslinger-messenger/python/postRegistration.py

**Comment by tenmalin** [comment]
For the new fields, the current implementation already satisfies the requirement to attach signature and public key, but just attach submission token still. It could be removed in the next binary push.

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/bea826fa704ad5fac6f5001e25768a27b77b264a
