### ISSUE TITLE
deleting a contact crashes app

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#79]
Tested on iOS 8.3 and iOS 6.1.6. To reproduce:
1. In Messages tab, tap "+" button.
2. Swipe left on any contact and tap Delete.
3. Crash.

**Comment by mwfarb** [comment]
I should add, after restarting the app and logging in, to check if delete worked, the recipient is actually removed from the list. Tested on 1.8.2 development branch https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/a4d10cefcbb3b6775d1a1c5c9ec3eef96f979da7.

**Comment by mwfarb** [comment]
Production version 1.8.1 does not crash.

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/ed237075423ae974651a303367f8d0df2f67ce98
