### ISSUE TITLE
remove support for iOS 6

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#84]
This will allow the layout to the auto-sized more universally I believe. iOS 6 is only running in the iPhone 3GS of all the phone-type devices anymore. It seems that iOS 7 is still popular, maybe since iOS 8 download is so large.

http://david-smith.org/iosversionstats
http://en.wikipedia.org/wiki/List_of_iOS_devices

**Comment by tenmalin** [comment]
@mwfarb remove iOS 6 will remove lots of customization code not just for customized layout. APIs related privacy control, contact access, and other stuffs will be removed.

**Comment by mwfarb** [comment]
That will be a very good thing. :+1:

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/e327ccea4da8456e6bbee9fa2ba3a165743646d5.
