### ISSUE TITLE
test NSURLSession security in iOS9

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#85]
In Platforms State of the Union 2015 at about 00:30-00:35, standard networking connections using NSURLSession in iOS 9 are now enforcing TLS 1.2 and forward secrecy, so it would be good to test on iOS 9 to make sure we're getting the benefits and it still works well. We can probably get some quick feedback by just testing the SafeSlinger developer demo server connections during the exchange protocol running on the simulator for iOS 9.

https://developer.apple.com/videos/wwdc/2015/?id=102.

That part of the session also mentioned that all iOS 9 apps submitted to the app store are required to support IPv6, so it would be good to test with Xcode 7 at least.

**Comment by tenmalin** [comment]
NSURLConnection has been replaced with NSURLSession. Also, session configuration only allows minimum version equivalent or above TLS 1.2. Close in  https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/ebc64f6a227aebc2d20c85d78424e165e30c0fac.
