### ISSUE TITLE
crash in ContactManageView

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#87]
Crashlytics #141	
SafeSlinger 1.8.2 (1.8.2.2)
edu.cmu.cylab.safeslinger.app
ContactManageView.m line 121
__36-[ContactManageView viewWillAppear:]_block_invoke
iPhone 4
iOS 7.1.2
Thread : Crashed: com.apple.root.default-priority
0  AppSupport                     0x32f92cda CPRecordStoreGetDatabase + 5
1  AppSupport                     0x32f9295f _getReaderConnection + 10
2  AppSupport                     0x32f9295f _getReaderConnection + 10
3  AppSupport                     0x32f94e6b CPRecordStoreProcessQueryWithBindBlock + 22
4  AppSupport                     0x32f94f1f CPRecordStoreCopyAllInstancesOfClassWhereWithBindBlock + 98
5  AddressBook                    0x2eb9a1ad ABCCopyArrayOfAllPeopleInSourceWithSortOrdering + 136
6  SafeSlinger                    0x000beee7 __36-[ContactManageView viewWillAppear:]_block_invoke (ContactManageView.m:121)
7  AddressBook                    0x2ebdc6a7 __37-[ABTCC accessRequestWithCompletion:]_block_invoke + 26
8  libdispatch.dylib              0x3a273833 _dispatch_call_block_and_release + 10
9  libdispatch.dylib              0x3a286921 _dispatch_root_queue_drain + 224
10 libdispatch.dylib              0x3a286b21 _dispatch_worker_thread2 + 56
11 libsystem_pthread.dylib        0x3a3b5bd3 _pthread_wqthread + 298

**Comment by tenmalin** [comment]
Same issue as https://github.com/SafeSlingerProject/SafeSlinger-iOS/issues/91.
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/d54b37a90ff4ee94ea17a8e24d364a0f82aa364d.
