### ISSUE TITLE
crash during decryptCipherMessage

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#89]
Crashlytics #139
SafeSlinger 1.8.2 (1.8.2.2)
edu.cmu.cylab.safeslinger.app
iPhone 6 Plus
iOS 8.3
SafeSlinger
EVP_PKEY_get1_RSA
Thread : Crashed: com.apple.root.default-qos
0  SafeSlinger                    0x000000010015f6a4 EVP_PKEY_get1_RSA
1  SafeSlinger                    0x00000001000c58ac +[SSEngine Decrypt:withPrikey:] (SSEngine.m:338)
2  SafeSlinger                    0x00000001000c58ac +[SSEngine Decrypt:withPrikey:] (SSEngine.m:338)
3  SafeSlinger                    0x00000001000c7948 +[SSEngine UnpackMessage:PubKey:Prikey:] (SSEngine.m:906)
4  SafeSlinger                    0x00000001000da4e4 +[MessageDecryptor decryptCipherMessage:] (MessageDecryptor.m:52)
5  SafeSlinger                    0x00000001000da168 __35+[MessageDecryptor tryToDecryptAll]_block_invoke (MessageDecryptor.m:23)
6  libdispatch.dylib              0x0000000195135994 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x0000000195135954 _dispatch_client_callout + 16
8  libdispatch.dylib              0x0000000195142780 _dispatch_root_queue_drain + 1848
9  libdispatch.dylib              0x0000000195143c4c _dispatch_worker_thread3 + 108
10 libsystem_pthread.dylib        0x000000019531522c _pthread_wqthread + 816

**Comment by tenmalin** [comment]
Add additional NULL check for RSA private key loading.
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/8da3c6ec6dd870588cf12d2f272649c8903a6545
