### ISSUE TITLE
crash during auto-decrypt when moving messages

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#96]
SafeSlinger 1.8.2 (1.8.2.2)
edu.cmu.cylab.safeslinger.app
Issue #150
UniversalDB.m line 393
-[UniversalDB DeleteMessage:]
iPhone 6 Plus
iOS 8.4
Thread : Crashed: com.apple.root.default-qos
0  libsqlite3.dylib               0x000000019833f348 (null) + 8392
1  libsqlite3.dylib               0x000000019833f238 (null) + 8120
2  libsqlite3.dylib               0x00000001983598ac (null) + 7364
3  libsqlite3.dylib               0x0000000198357df8 sqlite3_step + 528
4  SafeSlinger                    0x00000001000b4c84 -[UniversalDB DeleteMessage:] (UniversalDB.m:393)
5  SafeSlinger                    0x00000001000b2b38 +[MessageDecryptor decryptCipherMessage:] (MessageDecryptor.m:154)
6  SafeSlinger                    0x00000001000b2168 __35+[MessageDecryptor tryToDecryptAll]_block_invoke (MessageDecryptor.m:23)
7  libdispatch.dylib              0x0000000198645994 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x0000000198645954 _dispatch_client_callout + 16
9  libdispatch.dylib              0x0000000198652780 _dispatch_root_queue_drain + 1848
10 libdispatch.dylib              0x0000000198653c4c _dispatch_worker_thread3 + 108
11 libsystem_pthread.dylib        0x000000019882522c _pthread_wqthread + 816

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/2b3859686d7f7cfc43201d3e522a2c8b2085dd67.
