### ISSUE TITLE
crash during database key id lookup for display

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#97]
SafeSlinger 1.8.2 (1.8.2.2)
edu.cmu.cylab.safeslinger.app
Issue #151
SafeSlingerDB.m line 520
-[SafeSlingerDB QueryStringInTokenTableByKeyID:Field:]
iPhone 6
iOS 8.4
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000067736d73
0  libsqlite3.dylib               0x000000019676a3d0 (null) + 8164
1  libsqlite3.dylib               0x0000000196724190 (null) + 4176
2  libsqlite3.dylib               0x0000000196724190 (null) + 4176
3  libsqlite3.dylib               0x000000019672394c (null) + 2060
4  SafeSlinger                    0x000000010012331c -[SafeSlingerDB QueryStringInTokenTableByKeyID:Field:] (SafeSlingerDB.m:520)
5  SafeSlinger                    0x000000010013a2a4 -[MessageView tableView:cellForRowAtIndexPath:] (MessageView.m:158)
6  UIKit                          0x00000001894719fc -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 544
7  UIKit                          0x0000000189465824 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2364
8  UIKit                          0x00000001892511fc -[UITableView layoutSubviews] + 172
9  UIKit                          0x000000018916d6f4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 580
10 QuartzCore                     0x0000000188aa9db8 -[CALayer layoutSublayers] + 152
11 QuartzCore                     0x0000000188aa4820 CA::Layer::layout_if_needed(CA::Transaction*) + 320
12 QuartzCore                     0x0000000188aa46c4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
13 QuartzCore                     0x0000000188aa3e58 CA::Context::commit_transaction(CA::Transaction*) + 276
14 QuartzCore                     0x0000000188aa3bd8 CA::Transaction::commit() + 528
15 QuartzCore                     0x0000000188a9d300 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
16 CoreFoundation                 0x00000001846b02a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
17 CoreFoundation                 0x00000001846ad230 __CFRunLoopDoObservers + 360
18 CoreFoundation                 0x00000001846ad610 __CFRunLoopRun + 836
19 CoreFoundation                 0x00000001845d92d4 CFRunLoopRunSpecific + 396
20 GraphicsServices               0x000000018e02f6fc GSEventRunModal + 168
21 UIKit                          0x00000001891d6f40 UIApplicationMain + 1488
22 SafeSlinger                    0x000000010012ed60 main (main.m:33)
23 libdyld.dylib                  0x0000000196a6ea08 start + 4

**Comment by tenmalin** [comment]
Should be already fixed in the current version.
