### ISSUE TITLE
crash during message database load

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#98]
edu.cmu.cylab.safeslinger.app
1.8.2.2
Issue #155
UniversalDB.m line 429
-[UniversalDB LoadThreadMessage:]
iPhone 6 Plus
iOS 8.4
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000074
0  libsqlite3.dylib               0x00000001978963d0 (null) + 8164
1  libsqlite3.dylib               0x000000019786c3a4 (null) + 6544
2  libsqlite3.dylib               0x000000019786c3a4 (null) + 6544
3  libsqlite3.dylib               0x00000001978733f8 (null) + 35300
4  libsqlite3.dylib               0x0000000197872194 (null) + 30592
5  libsqlite3.dylib               0x00000001978fd4b8 (null) + 227956
6  libsqlite3.dylib               0x000000019786ce54 (null) + 9280
7  libsqlite3.dylib               0x0000000197852110 (null) + 12240
8  libsqlite3.dylib               0x00000001978511d8 (null) + 8344
9  libsqlite3.dylib               0x00000001978504d0 (null) + 5008
10 libsqlite3.dylib               0x000000019784fca4 (null) + 2916
11 libsqlite3.dylib               0x000000019784f94c (null) + 2060
12 SafeSlinger                    0x00000001000f0ebc -[UniversalDB LoadThreadMessage:] (UniversalDB.m:429)
13 SafeSlinger                    0x00000001000b08c8 -[MessageDetailView reloadTable] (MessageDetailView.m:208)
14 SafeSlinger                    0x00000001000b0c94 -[MessageDetailView viewWillAppear:] (MessageDetailView.m:238)
15 UIKit                          0x000000018a2abf08 -[UIViewController _setViewAppearState:isAnimating:] + 516
16 UIKit                          0x000000018a4372bc -[UINavigationController _startCustomTransition:] + 916
17 UIKit                          0x000000018a349e84 -[UINavigationController _startDeferredTransitionIfNeeded:] + 468
18 UIKit                          0x000000018a349c50 -[UINavigationController __viewWillLayoutSubviews] + 56
19 UIKit                          0x000000018a349bd0 -[UILayoutContainerView layoutSubviews] + 200
20 UIKit                          0x000000018a2916f4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 580
21 QuartzCore                     0x0000000189bcddb8 -[CALayer layoutSublayers] + 152
22 QuartzCore                     0x0000000189bc8820 CA::Layer::layout_if_needed(CA::Transaction*) + 320
23 QuartzCore                     0x0000000189bc86c4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
24 QuartzCore                     0x0000000189bc7e58 CA::Context::commit_transaction(CA::Transaction*) + 276
25 QuartzCore                     0x0000000189bc7bd8 CA::Transaction::commit() + 528
26 QuartzCore                     0x0000000189bc1300 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
27 CoreFoundation                 0x00000001857d42a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
28 CoreFoundation                 0x00000001857d1230 __CFRunLoopDoObservers + 360
29 CoreFoundation                 0x00000001857d1610 __CFRunLoopRun + 836
30 CoreFoundation                 0x00000001856fd2d4 CFRunLoopRunSpecific + 396
31 GraphicsServices               0x000000018f1536fc GSEventRunModal + 168
32 UIKit                          0x000000018a2faf40 UIApplicationMain + 1488
33 SafeSlinger                    0x00000001000ead60 main (main.m:33)
34 libdyld.dylib                  0x0000000197b9aa08 start + 4

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/2b3859686d7f7cfc43201d3e522a2c8b2085dd67.
