### ISSUE TITLE
crash during message view navigation

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-iOS#99]
edu.cmu.cylab.safeslinger.app
1.8.2.2
Issue #156
MessageDetailView.m line 597
-[MessageDetailView alertView:didDismissWithButtonIndex:]
iPhone 6
iOS 8.4
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
0  CoreFoundation                 0x00000001838cc2d8 __exceptionPreprocess + 132
1  libobjc.A.dylib                0x00000001955980e4 objc_exception_throw + 60
2  CoreFoundation                 0x00000001837b2f70 -[__NSPlaceholderArray initWithObjects:count:] + 412
3  CoreFoundation                 0x00000001837bf200 +[NSArray arrayWithObjects:count:] + 60
4  SafeSlinger                    0x0000000100017cf8 -[MessageDetailView alertView:didDismissWithButtonIndex:] (MessageDetailView.m:597)
5  UIKit                          0x000000018872aa44 __76-[UIAlertView _performPresentationDismissalWithClickedButtonIndex:animated:]_block_invoke + 76
6  UIKit                          0x0000000188a863a0 -[_UIAlertControllerShimPresenter _dismissAlertControllerAnimated:completion:] + 336
7  UIKit                          0x000000018872a9c0 -[UIAlertView _performPresentationDismissalWithClickedButtonIndex:animated:] + 224
8  UIKit                          0x00000001887229f8 -[UIAlertController _fireOffActionOnTargetIfValidForAction:] + 68
9  UIKit                          0x000000018872300c __85-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:]_block_invoke + 36
10 UIKit                          0x000000018864ac44 -[UIPresentationController transitionDidFinish:] + 1328
11 UIKit                          0x000000018864d0c0 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke_2 + 168
12 UIKit                          0x0000000188466f64 -[_UIViewControllerTransitionContext completeTransition:] + 132
13 UIKit                          0x000000018837c708 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 408
14 UIKit                          0x000000018837c270 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 188
15 UIKit                          0x000000018837c178 -[UIViewAnimationState animationDidStop:finished:] + 104
16 QuartzCore                     0x0000000187c8562c CA::Layer::run_animation_callbacks(void*) + 296
17 libdispatch.dylib              0x0000000195c15954 _dispatch_client_callout + 16
18 libdispatch.dylib              0x0000000195c1a20c _dispatch_main_queue_callback_4CF + 1608
19 CoreFoundation                 0x00000001838837f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
20 CoreFoundation                 0x00000001838818a0 __CFRunLoopRun + 1492
21 CoreFoundation                 0x00000001837ad2d4 CFRunLoopRunSpecific + 396
22 GraphicsServices               0x000000018d2036fc GSEventRunModal + 168
23 UIKit                          0x00000001883aaf40 UIApplicationMain + 1488
24 SafeSlinger                    0x000000010004ed60 main (main.m:33)
25 libdyld.dylib                  0x0000000195c42a08 start + 4

**Comment by tenmalin** [comment]
Already identify where the bug occurs: crash while a user plans to change her permissions while she tries to attach image via camera or photo album. The system firstly popups **Setup** dialog and crashes after she clicks **Settings** button (app tries to lead her to system settings).

**Comment by tenmalin** [comment]
Close in https://github.com/SafeSlingerProject/SafeSlinger-iOS/commit/03db869ea8164436d00633d948b0c1d8aeb21b6e.
